# Generated by Django 2.0.7 on 2018-07-29 22:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apartment_id', models.AutoField(primary_key=True, serialize=False)),
                ('apartment_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]*$', 'Shall Contain only alphabets and numbers')])),
                ('available_units', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]$', 'Shall contain only numerals')])),
                ('apartment_location', models.CharField(max_length=400, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]*$', 'Shall Contain only alphabets and numbers')])),
                ('apartment_description', models.CharField(max_length=400, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]*$', 'Shall Contain only alphabets and numbers')])),
                ('apartment_price', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]$', 'Shall contain only numerals')])),
                ('availability', models.CharField(choices=[('Y', 'available'), ('N', 'Non-not-available')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]$', 'Shall contain only alphabets')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]$', 'Shall contain only alphabets')])),
                ('email', models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator(message='Please check the email address')])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('(\\d{3}[-\\.\\s]??\\d{3}[-\\.\\s]??\\d{4}|\\(\\d{3}\\)\\s*\\d{3}[-\\.\\s]??\\d{4}|\\d{3}[-\\.\\s]??\\d{4})', 'Please check your phone number')])),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]*$', 'Shall Contain only alphabets and numbers')])),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apartments.owner'),
        ),
    ]
