# Generated by Django 2.0.7 on 2018-08-06 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_price',
            field=models.IntegerField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Shall contain only numerals')]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='available_units',
            field=models.IntegerField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Shall contain only numerals')]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='posession',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Shall contain only numerals')]),
        ),
    ]
