# Generated by Django 2.0.7 on 2018-08-06 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_alcohol',
            field=models.CharField(choices=[('A', 'Alcoholic'), ('N', 'Non-Alcoholic')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_smoke',
            field=models.CharField(choices=[('S', 'Smoker'), ('N', 'Non-Smoker')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_veg',
            field=models.CharField(choices=[('V', 'Vegetarian'), ('N', 'Non-Vegetarian')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='sharing_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Shall contain only numerals')]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_description',
            field=models.CharField(max_length=400, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]*$', 'Shall contain only alphabets')]),
        ),
    ]
