# Generated by Django 2.0.7 on 2018-08-08 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('Apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userClicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countOfClicks', models.IntegerField(blank=True, default=1, null=True)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apartments.Apartment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
            ],
        ),
    ]
