# Generated by Django 2.0.7 on 2018-08-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='car_parking',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No-Car-Parking')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='gym',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No-Gym')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='heater',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No-heater')], default='N', max_length=1),
        ),
    ]
