# Generated by Django 2.0.7 on 2018-08-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0002_auto_20180807_1522'),
        ('Apartments', '0002_auto_20180806_2231'),
    ]

    operations = [
    ]
