# Generated by Django 2.0.7 on 2018-08-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0002_auto_20180730_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='sharing',
            field=models.CharField(choices=[('Y', 'Sharing'), ('N', 'No-Sharing')], default='N', max_length=1),
        ),
    ]
