# Generated by Django 2.0.7 on 2018-08-08 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0003_merge_20180807_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='available_units',
            field=models.CharField(default=0, max_length=400, validators=[django.core.validators.RegexValidator('^[0-9,]*$', 'Should have numbers seperated by commas')]),
        ),
    ]
