# Generated by Django 2.0.7 on 2018-08-06 16:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0003_auto_20180806_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]*$', 'Shall contain only alphabets')]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='posession',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
