# Generated by Django 2.0.7 on 2018-08-06 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]$', 'Shall contain only alphabets')])),
                ('user_email', models.CharField(max_length=400, validators=[django.core.validators.EmailValidator(message='Please check the email address')])),
                ('user_password', models.CharField(max_length=400)),
                ('user_dob', models.CharField(max_length=10)),
                ('user_country', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]$', 'Shall contain only alphabets')])),
            ],
        ),
    ]
