# Generated by Django 2.0.7 on 2018-08-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0002_user_user_cpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_cpassword',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
