# Generated by Django 2.0.7 on 2018-08-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apartments', '0003_auto_20180806_1437'),
        ('feedback', '0003_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='apartment_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='apartment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Apartments.Apartment'),
        ),
    ]
